[package]
name = "supertux-mod-adventure-mode"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "AdventureMode"

[dependencies]
winapi = { version = "0.3", features = [
    "winuser",
    "processthreadsapi",
    "memoryapi",
    "libloaderapi",
] }
